/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colony;

import com.ant.nodedata.NodeDistance;
import com.ant.nodedata.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Thilina Thushantha
 */
public class Ant_Colony extends javax.swing.JFrame {

    /**
     * Creates new form Ant_Colony
     */
    Paths list;
    int[] arr = new int[25];
    int path2[] = new int[25];
    int TrueOrFalse = 0;

    public Ant_Colony() {

        initComponents();

//        arr = new ArrayList<Integer>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Node_1 = new javax.swing.JButton();
        Node_2 = new javax.swing.JButton();
        Node_3 = new javax.swing.JButton();
        Node_4 = new javax.swing.JButton();
        Node_5 = new javax.swing.JButton();
        Node_6 = new javax.swing.JButton();
        Node_7 = new javax.swing.JButton();
        Node_8 = new javax.swing.JButton();
        Node_9 = new javax.swing.JButton();
        Node_10 = new javax.swing.JButton();
        Node_15 = new javax.swing.JButton();
        Node_14 = new javax.swing.JButton();
        Node_12 = new javax.swing.JButton();
        Node_11 = new javax.swing.JButton();
        Node_13 = new javax.swing.JButton();
        Node_16 = new javax.swing.JButton();
        Node_17 = new javax.swing.JButton();
        Node_18 = new javax.swing.JButton();
        Node_19 = new javax.swing.JButton();
        Node_20 = new javax.swing.JButton();
        Node_21 = new javax.swing.JButton();
        Node_22 = new javax.swing.JButton();
        Node_23 = new javax.swing.JButton();
        Node_24 = new javax.swing.JButton();
        Node_25 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Node_1.setText("1");
        Node_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_1ActionPerformed(evt);
            }
        });

        Node_2.setText("2");
        Node_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_2ActionPerformed(evt);
            }
        });

        Node_3.setText("3");
        Node_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_3ActionPerformed(evt);
            }
        });

        Node_4.setText("4");
        Node_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_4ActionPerformed(evt);
            }
        });

        Node_5.setText("5");
        Node_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_5ActionPerformed(evt);
            }
        });

        Node_6.setText("6");
        Node_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_6ActionPerformed(evt);
            }
        });

        Node_7.setText("7");
        Node_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_7ActionPerformed(evt);
            }
        });

        Node_8.setText("8");
        Node_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_8ActionPerformed(evt);
            }
        });

        Node_9.setText("9");
        Node_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_9ActionPerformed(evt);
            }
        });

        Node_10.setText("10");
        Node_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_10ActionPerformed(evt);
            }
        });

        Node_15.setText("15");
        Node_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_15ActionPerformed(evt);
            }
        });

        Node_14.setText("14");
        Node_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_14ActionPerformed(evt);
            }
        });

        Node_12.setText("12");
        Node_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_12ActionPerformed(evt);
            }
        });

        Node_11.setText("11");
        Node_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_11ActionPerformed(evt);
            }
        });

        Node_13.setText("13");
        Node_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_13ActionPerformed(evt);
            }
        });

        Node_16.setText("16");
        Node_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_16ActionPerformed(evt);
            }
        });

        Node_17.setText("17");
        Node_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_17ActionPerformed(evt);
            }
        });

        Node_18.setText("18");
        Node_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_18ActionPerformed(evt);
            }
        });

        Node_19.setText("19");
        Node_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_19ActionPerformed(evt);
            }
        });

        Node_20.setText("20");
        Node_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_20ActionPerformed(evt);
            }
        });

        Node_21.setText("21");
        Node_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_21ActionPerformed(evt);
            }
        });

        Node_22.setText("22");
        Node_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_22ActionPerformed(evt);
            }
        });

        Node_23.setText("23");
        Node_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_23ActionPerformed(evt);
            }
        });

        Node_24.setText("24");
        Node_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_24ActionPerformed(evt);
            }
        });

        Node_25.setText("25");
        Node_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Node_25ActionPerformed(evt);
            }
        });

        jButton2.setText("Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Path1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("PAth 2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Test2 ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Node_21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Node_16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Node_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Node_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Node_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Node_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Node_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Node_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Node_11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Node_12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Node_13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Node_14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Node_15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Node_10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Node_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Node_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Node_15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Node_14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Node_11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Node_16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Node_21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Node_25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Node_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_17ActionPerformed
        arr[17] = 17;
    }//GEN-LAST:event_Node_17ActionPerformed

    private void Node_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_18ActionPerformed
        arr[18] = 18;
    }//GEN-LAST:event_Node_18ActionPerformed

    private void Node_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_19ActionPerformed
        arr[19] = 19;
    }//GEN-LAST:event_Node_19ActionPerformed

    private void Node_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_20ActionPerformed
        arr[20] = 20;
    }//GEN-LAST:event_Node_20ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        NodeDistance nod = new NodeDistance();
        String value = nod.nodeDistance(Node_1, Node_2, Node_3, Node_4, Node_5, Node_6, Node_7, Node_8, Node_9, Node_10, Node_1, Node_12, Node_13, Node_14, Node_15, Node_16, Node_17, Node_18, Node_19, Node_20, Node_21, Node_22, Node_23, Node_24, Node_25);

    }//GEN-LAST:event_formWindowOpened

    private void Node_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_1ActionPerformed
        if (TrueOrFalse == 1) {
            arr[1] = 1;
        } else if (TrueOrFalse == 2) {
            path2[1] = 1;
        }


    }//GEN-LAST:event_Node_1ActionPerformed

    private void Node_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_2ActionPerformed

        if (TrueOrFalse == 1) {
            arr[2] = 2;
        } else if (TrueOrFalse == 2) {
            path2[2] = 2;
        }


    }//GEN-LAST:event_Node_2ActionPerformed

    private void Node_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_3ActionPerformed

        if (TrueOrFalse == 1) {
            arr[3] = 3;
        } else if (TrueOrFalse == 2) {
            path2[3] = 3;
        }

    }//GEN-LAST:event_Node_3ActionPerformed

    private void Node_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_4ActionPerformed

        if (TrueOrFalse == 1) {
            arr[4] = 4;
        } else if (TrueOrFalse == 2) {
            path2[4] = 4;
        }
    }//GEN-LAST:event_Node_4ActionPerformed

    private void Node_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_5ActionPerformed

        if (TrueOrFalse == 1) {
            arr[5] = 5;
        } else if (TrueOrFalse == 2) {
            path2[5] = 5;
        }
    }//GEN-LAST:event_Node_5ActionPerformed

    private void Node_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_6ActionPerformed

        if (TrueOrFalse == 1) {
            arr[6] = 6;
        } else if (TrueOrFalse == 2) {
            path2[6] = 6;
        }
    }//GEN-LAST:event_Node_6ActionPerformed

    private void Node_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_7ActionPerformed

        if (TrueOrFalse == 1) {
            arr[7] = 7;
        } else if (TrueOrFalse == 2) {
            path2[7] = 7;
        }
    }//GEN-LAST:event_Node_7ActionPerformed

    private void Node_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_8ActionPerformed

        if (TrueOrFalse == 1) {
            arr[8] = 8;
        } else if (TrueOrFalse == 2) {
            path2[8] = 8;
        }
    }//GEN-LAST:event_Node_8ActionPerformed

    private void Node_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_9ActionPerformed

        if (TrueOrFalse == 1) {
            arr[9] = 9;
        } else if (TrueOrFalse == 2) {
            path2[9] = 9;
        }
    }//GEN-LAST:event_Node_9ActionPerformed

    private void Node_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_10ActionPerformed

        if (TrueOrFalse == 1) {
            arr[10] = 10;
        } else if (TrueOrFalse == 2) {
            path2[10] = 10;
        }
    }//GEN-LAST:event_Node_10ActionPerformed

    private void Node_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_11ActionPerformed

        if (TrueOrFalse == 1) {
            arr[11] = 11;
        } else if (TrueOrFalse == 2) {
            path2[11] = 11;
        }
    }//GEN-LAST:event_Node_11ActionPerformed

    private void Node_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_12ActionPerformed

        if (TrueOrFalse == 1) {
            arr[12] = 12;
        } else if (TrueOrFalse == 2) {
            path2[12] = 12;
        }
    }//GEN-LAST:event_Node_12ActionPerformed

    private void Node_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_13ActionPerformed

        if (TrueOrFalse == 1) {
            arr[13] = 13;
        } else if (TrueOrFalse == 2) {
            path2[13] = 13;
        }
    }//GEN-LAST:event_Node_13ActionPerformed

    private void Node_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_14ActionPerformed

        if (TrueOrFalse == 1) {
            arr[14] = 14;
        } else if (TrueOrFalse == 2) {
            path2[14] = 14;
        }
    }//GEN-LAST:event_Node_14ActionPerformed

    private void Node_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_15ActionPerformed

        if (TrueOrFalse == 1) {
            arr[15] = 15;
        } else if (TrueOrFalse == 2) {
            path2[15] = 15;
        }
    }//GEN-LAST:event_Node_15ActionPerformed

    private void Node_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_16ActionPerformed

        if (TrueOrFalse == 1) {
            arr[16] = 16;
        } else if (TrueOrFalse == 2) {
            path2[16] = 16;
        }
    }//GEN-LAST:event_Node_16ActionPerformed

    private void Node_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_21ActionPerformed

        if (TrueOrFalse == 1) {
            arr[21] = 21;
        } else if (TrueOrFalse == 2) {
            path2[21] = 21;
        }
    }//GEN-LAST:event_Node_21ActionPerformed

    private void Node_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_22ActionPerformed

        if (TrueOrFalse == 1) {
            arr[22] = 22;
        } else if (TrueOrFalse == 2) {
            path2[22] = 22;
        }
    }//GEN-LAST:event_Node_22ActionPerformed

    private void Node_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_23ActionPerformed

        if (TrueOrFalse == 1) {
            arr[23] = 23;
        } else if (TrueOrFalse == 2) {
            path2[23] = 23;
        }
    }//GEN-LAST:event_Node_23ActionPerformed

    private void Node_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_24ActionPerformed

        if (TrueOrFalse == 1) {
            arr[24] = 24;
        } else if (TrueOrFalse == 2) {
            path2[24] = 24;
        }
    }//GEN-LAST:event_Node_24ActionPerformed

    private void Node_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Node_25ActionPerformed

        if (TrueOrFalse == 1) {
            arr[25] = 25;
        } else if (TrueOrFalse == 2) {
            path2[25] = 25;
        }
    }//GEN-LAST:event_Node_25ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (TrueOrFalse == 0) {
            TrueOrFalse = 1;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (TrueOrFalse == 0) {
            TrueOrFalse = 2;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TrueOrFalse = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int pathcost2 = 0;
        int pathcost1 = 0;
        for (int i = 0; i < path2.length; i++) {
             
            if (path2[i] != 0) {
                pathcost2++;
            }

        }
        System.out.println("Path cost2 -" + pathcost2);
        
        
        for (int i = 0; i < arr.length; i++) {
             
            if (arr[i] != 0) {
                pathcost1++;
            }

        }
        System.out.println("path 1 cost -" + pathcost1);
        
        if(pathcost1 > pathcost2){
            System.out.println("Path 2 is the best way");
        }else if (pathcost1 < pathcost2){
            System.out.println("Path 1 is the best way");
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ant_Colony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ant_Colony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ant_Colony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ant_Colony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ant_Colony().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Node_1;
    private javax.swing.JButton Node_10;
    private javax.swing.JButton Node_11;
    private javax.swing.JButton Node_12;
    private javax.swing.JButton Node_13;
    private javax.swing.JButton Node_14;
    private javax.swing.JButton Node_15;
    private javax.swing.JButton Node_16;
    private javax.swing.JButton Node_17;
    private javax.swing.JButton Node_18;
    private javax.swing.JButton Node_19;
    private javax.swing.JButton Node_2;
    private javax.swing.JButton Node_20;
    private javax.swing.JButton Node_21;
    private javax.swing.JButton Node_22;
    private javax.swing.JButton Node_23;
    private javax.swing.JButton Node_24;
    private javax.swing.JButton Node_25;
    private javax.swing.JButton Node_3;
    private javax.swing.JButton Node_4;
    private javax.swing.JButton Node_5;
    private javax.swing.JButton Node_6;
    private javax.swing.JButton Node_7;
    private javax.swing.JButton Node_8;
    private javax.swing.JButton Node_9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
